import Image from 'next/image';

const phone = '9421107110';
const whatsapp = `https://wa.me/91${phone}?text=${encodeURIComponent('Hello, I want to enquire about borewell service in Kolhapur.')}`;
const directions = 'https://maps.app.goo.gl/Q7eD3jaKAxFDEyPf8?g_st=aw';

function Arrow() { return <span aria-hidden="true">↗</span>; }

export default function Home() {
  return <>
    <header className="header"><a className="brand" href="#top"><i className="drop"/><span><b>Pawar Borewell&apos;s</b><small>&amp; Trader&apos;s · Kolhapur</small></span></a><div className="header-actions"><a className="directions-link" href={directions} target="_blank" rel="noopener">Location ↗</a><a className="top-call" href={`tel:+91${phone}`}>Call now</a></div></header>
    <main id="top">
      <section className="hero"><Image className="hero-image" src="/assets/drilling-site.jpeg" fill priority sizes="(max-width: 700px) 65vw, 45vw" alt="Pawar Borewell drilling rig at a Kolhapur site"/><div className="hero-shade"/><div className="shell hero-content"><p className="kicker light">Serving Kolhapur city &amp; district</p><h1>Water starts with the <em>right</em> borewell.</h1><p className="lead">Trusted drilling and water solutions for homes, farms, businesses and industries across Kolhapur.</p><div className="actions"><a className="button white" href={`tel:+91${phone}`}>Call {phone.slice(0,5)} {phone.slice(5)} <Arrow/></a><a className="simple-link" href="#services">Explore services ↓</a></div><div className="stats"><div><b>Kolhapur</b><span>local expertise</span></div><div><b>Site Visit</b><span>guided support</span></div><div><b>Quality</b><span>workmanship</span></div></div></div></section>
      <section className="shell intro"><p className="kicker">Dependable water solutions</p><div><h2>Built for the ground beneath <em>Kolhapur.</em></h2><p>Every site is different. We combine practical local knowledge with careful work, from a first inspection to a working borewell.</p></div></section>
      <section className="services" id="services"><div className="shell"><div className="section-head"><div><p className="kicker">What we do</p><h2>One team. Every step.</h2></div><p>Reliable work planned around your site—at home, on the farm or for commercial work.</p></div><div className="cards"><article className="card featured"><small>01</small><i>⌄</i><h3>Borewell drilling</h3><p>Professional drilling for homes, commercial buildings, farms and industrial sites.</p><a href={whatsapp} target="_blank">Ask on WhatsApp →</a></article><article className="card"><small>02</small><i>⌂</i><h3>Home &amp; commercial</h3><p>Water solutions for personal homes, apartments, shops and commercial spaces.</p></article><article className="card"><small>03</small><i>⌇</i><h3>Agricultural borewells</h3><p>Dependable support for farms, irrigation and agricultural water needs.</p></article></div></div></section>
      <section className="shell products"><div className="product-photo"><Image src="/assets/submersible-pumps.jpeg" fill sizes="(max-width: 700px) 100vw, 50vw" alt="Submersible pumps and borewell pump equipment"/></div><div><p className="kicker">Pumps, pipes &amp; parts</p><h2>Everything your borewell needs.</h2><p>Along with drilling, we supply essential borewell materials and parts to complete your water system with confidence.</p><ul><li>Submersible pumps and pump accessories</li><li>Borewell pipes and fittings</li><li>Essential borewell parts and materials</li><li>Product guidance for your requirement</li></ul><a className="button dark" href={whatsapp} target="_blank">Ask about materials <Arrow/></a></div></section>
      <section className="showcase"><div className="shell showcase-grid"><div><p className="kicker">Work in progress</p><h2>Real work.<br/><em>Reliable water solutions.</em></h2><p>Our on-site team brings the right equipment and focused workmanship to every project.</p></div><figure><Image src="/assets/night-drilling.jpeg" fill sizes="(max-width: 700px) 100vw, 58vw" alt="Pawar Borewell team working on a drilling project at night"/><figcaption>On-site drilling support across Kolhapur.</figcaption></figure></div></section>
      <section className="shell coverage"><div><p className="kicker">Our service area</p><h2>Across Kolhapur,<br/><em>wherever you need water.</em></h2><p className="location-copy">Visit Pawar Borewell&apos;s &amp; Trader&apos;s at R.B. Patil Colony, Mudshingi.</p><a className="location-button" href={directions} target="_blank" rel="noopener">Get directions <Arrow/></a></div><a className="map" href={directions} target="_blank" rel="noopener" aria-label="Get directions to Pawar Borewell's and Trader's"><b>● &nbsp;Kolhapur</b><span>R.B. Patil Colony, Mudshingi</span><small>Open in Google Maps ↗</small></a></section>
      <section className="shell callout"><div><p className="kicker">Let&apos;s talk water</p><h2>Need a borewell service in Kolhapur?</h2><p>Get in touch for a site discussion. We&apos;ll help you understand the best next step.</p></div><div><a className="button dark" href={`tel:+91${phone}`}>Call {phone.slice(0,5)} {phone.slice(5)} <Arrow/></a><a className="button outline" href={whatsapp} target="_blank">WhatsApp us <Arrow/></a></div></section>
    </main>
    <footer><div className="shell footer"><a className="brand" href="#top"><i className="drop"/><span><b>Pawar Borewell&apos;s</b><small>&amp; Trader&apos;s · Kolhapur</small></span></a><p><a href={directions} target="_blank" rel="noopener">R.B. Patil Colony, Mudshingi, Kolhapur ↗</a><br/>© {new Date().getFullYear()} Pawar Borewell&apos;s &amp; Trader&apos;s</p><a href={`tel:+91${phone}`}>{phone}</a></div></footer>
    <nav className="mobile-nav"><a href={`tel:+91${phone}`}>☎ &nbsp; Call now</a><a href={whatsapp} target="_blank">◔ &nbsp; WhatsApp</a></nav>
  </>;
}
